# Specify the base image with Python and environment setup
image: python:3.11

# Define stages for your CI/CD pipeline
stages:
  - test

# Define job for running tests
test:
  stage: test
  script:
    - echo "Running tests..."
    - python -m unittest tests
