from enum import Enum

# Enum class for slide layouts

class SlideEnum(Enum):
    # Define constants for slide layouts
    SLIDE_TITLE_LAYOUT = 0
    SLIDE_TITLE_AND_CONTENT_LAYOUT = 1
    SLIDE_SECTION_HEADER_LAYOUT = 2
    SLIDE_TWO_CONTENT_LAYOUT = 3
    SLIDE_COMPARISON_LAYOUT = 4
    SLIDE_TITLE_ONLY_LAYOUT = 5
    SLIDE_BLANK_LAYOUT = 6
    SLIDE_CONTENT_WITH_CAPTION_LAYOUT = 7
    SLIDE_PICTURE_WITH_CAPTION_LAYOUT = 8

